version: '3.7'
services:
  node:
    image: node:14-alpine
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./docker/pop-size-conversion-client:/usr/app/client
    tty: true
    stdin_open: true
    working_dir: /usr/app/client
    command: /bin/sh -c "yarn install && yarn start"
    ports:
      - "3001:3001"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/usr/share/nginx/html

  swagger-watch:
    build: ./swagger-watch
    volumes:
      - ./swagger-watch:/app
      - /app/node_modules
      - ./swagger:/swagger
      - ./docs/swagger.yml:/docs/swagger.yml
    working_dir: /app
    command: 'node index.js'

  swagger-nginx:
    image: openresty/openresty:alpine
    ports:
      - "8081:8090"
    volumes:
      - ./docker/nginx/swagger.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - swagger-watch
