swagger: "2.0"
info:
  title: "Pop Size Conversion"
  description: "Pop Size Conversion\n
  陳列棚に並ぶPOPのサイズ変更を楽々に作れます。\n"
  version: "1.0.0"
host: "localhost:8080"
tags:
  - name: users
    description: ユーザ関連API
  - name: items
    description: 商品関連API
  - name: categories
    description: 商品カテゴリ関連API
  - name: pops
    description: POP情報関連API
schemes:
  - "http"
paths:
  /items:
    post:
      tags:
        - items
      summary: 商品情報を登録
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            $ref: "#/definitions/ItemListResponse"
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/ItemListResponse"
  /item/{itemId}:
    get:
      tags:
        - items
      summary: 商品情報詳細を取得
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: item_id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/ItemGetResponse"
    put:
      tags:
        - items
      summary: 商品情報を更新
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: item_id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/ItemGetResponse"

definitions:
  ItemListResponse:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/ItemGetResponse"
  ItemGetResponse:
    type: object
    properties:
      id:
        type: integer
        description: 商品ID
        example: 123
      name:
        type: string
        description: 商品名
        example: ポテトチップス Mサイズ
      description:
        type: string
        description: 商品説明
        example: 各種
      addition:
        type: string
        description: 補足
        example: ""
      onlyOneDay:
        type: boolean
        description: 限定
        example: false
      code:
        type: integer
        description: JANコード
        example: 4901330532901
      category:
        $ref: "#/definitions/CategoryGetResponse"
      pop:
        type: array
        items:
          $ref: "#/definitions/PopGetResponse"
  CategoryGetResponse:
    type: object
    properties:
      id:
        type: integer
        description: カテゴリーID
        example: 2
      name:
        type: string
        description: カテゴリー名
        example: 菓子
  PopListResponse:
    type: object
    properties:
      pop:
        type: array
        items:
          $ref: "#/definitions/PopGetResponse"
  PopGetResponse:
    type: object
    properties:
      id:
        type: integer
        description: POP ID
        example: 1
      name:
        type: string
        description: POP名
        example: 広告の品
      price:
        type: integer
        description: 本体価格
        example: 78
      taxPrice:
        type: integer
        description: 税込価格
        example: 85
      size:
        type: array
        items:
          $ref: "#/definitions/SizeGetResponse"
  SizeGetResponse:
    type: object
    properties:
      id:
        type: integer
        description: サイズID
        example: 1
      paperSize:
        type: string
        description: サイズ
        example: A4
      baseImage:
        type: string
        description: 元画像
        example: 0001.jpeg
