swagger: "2.0"
info:
  title: "Pop Size Conversion"
  description: "Pop Size Conversion\n
  陳列棚に並ぶPOPのサイズ変更を楽々に作れます。\n"
  version: "1.0.0"
host: "localhost:8080"
tags:
  - name: accounts
    description: ユーザ関連API
  - name: pops
    description: POP情報関連API
  - name: items
    description: 商品関連API
  - name: categories
    description: 商品カテゴリ関連API
schemes:
  - https
  - http
paths:
  /accounts:
    post:
      tags:
        - accounts
      security:
        - tokenAuth: []
      summary: Creating an account
      description: ""
      operationId: addAccount
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: Request Body
          required: true
          schema:
            $ref: "#/definitions/AccountCreateRequest"
      responses:
        "200":
          description: Successful login
          schema:
            $ref: "#/definitions/AccountCreateResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/400BadRequestError"
  "/accounts/{username}":
    get:
      tags:
        - accounts
      summary: Fetching an account
      description: ""
      operationId: findAccountByID
      parameters:
        - name: username
          in: path
          description: Username of account to return
          required: true
          type: string
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/AccountCreateResponse"
  /pops:
    get:
      tags:
        - pops
      summary: ポップ一覧を取得
      description: ""
      operationId: getPops
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/PopListResponse"
    post:
      tags:
        - pops
      summary: ポップの作成
      description: ""
      operationId: createPops
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/PopListResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/400BadRequestError"
  "/pop/{id}":
    get:
      tags:
        - pops
      summary: ポップ詳細を取得
      description: ""
      operationId: getPop
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/PopResponse"
    put:
      tags:
        - pops
      summary: ポップ情報を更新
      description: ""
      operationId: updatePop
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/PopResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/400BadRequestError"
    delete:
      tags:
        - pops
      summary: ポップを削除
      description: ""
      operationId: deletePop
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
  /item:
    post:
      tags:
        - items
      summary: 商品情報を作成
      description: ""
      operationId: createItem
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/ItemResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/400BadRequestError"
  "/item/{id}":
    get:
      tags:
        - items
      summary: 商品情報詳細を取得
      description: ""
      operationId: getItem
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/ItemResponse"
    put:
      tags:
        - items
      summary: 商品情報を更新
      description: ""
      operationId: updateItem
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/ItemResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/400BadRequestError"
    delete:
      tags:
        - items
      summary: 商品情報を削除
      description: ""
      operationId: deleteItem
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
  /category:
    post:
      tags:
        - categories
      summary: 商品カテゴリを追加
      description: ""
      operationId: addCategory
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/CategoryResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/400BadRequestError"
  "/category/{id}":
    get:
      tags:
        - categories
      summary: 商品カテゴリを取得
      description: ""
      operationId: getCategory
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/CategoryResponse"
    delete:
      tags:
        - categories
      summary: 商品カテゴリの削除
      description: ""
      operationId: removeCategory
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
  /size:
    post:
      tags:
        - pops
      summary: ポップサイズを追加
      description: ""
      operationId: addSize
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/SizeResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/400BadRequestError"
  "/size/{id}":
    get:
      tags:
        - pops
      summary: ポップサイズを取得
      description: ""
      operationId: getSize
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: "#/definitions/SizeResponse"
    delete:
      tags:
        - pops
      summary: ポップサイズの削除
      description: ""
      operationId: removeSize
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          type: integer
      responses:
        "200":
          description: A successful response.
          schema:
            type: object

securityDefinitions:
  tokenAuth:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountCreateRequest:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
        example: cygnu
      password:
        type: string
        example: P@ssw0rd
  AccountCreateResponse:
    type: object
    properties:
      id:
        type: integer
      username:
        type: string
        example: cygnu
      password:
        type: string
        example: P@ssw0rd
      createdAt:
        type: string
        format: date-time
  PopListResponse:
    type: object
    properties:
      pop:
        type: array
        items:
          $ref: "#/definitions/PopResponse"
  PopResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
        example: 広告の品
      addition:
        type: string
        example: ""
      date:
        type: string
        format: date
      isOneDay:
        type: boolean
        example: false
      price:
        type: integer
        example: 78
      taxPrice:
        type: integer
        example: 85
      item:
        $ref: "#/definitions/ItemResponse"
      size:
        type: array
        items:
          $ref: "#/definitions/SizeResponse"
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  ItemResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
        example: ポテトチップス Mサイズ
      description:
        type: string
        example: 各種
      code:
        type: integer
        example: 4901330532901
      category:
        $ref: "#/definitions/CategoryResponse"
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  CategoryResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
        example: 菓子
      createdOn:
        type: string
        format: date-time
  SizeResponse:
    type: object
    properties:
      id:
        type: integer
      paperSize:
        type: string
        example: A4
      baseImage:
        type: string
        example: 0001.jpeg
      createdOn:
        type: string
        format: date-time
  400BadRequestError:
    type: object
    properties:
      code:
        type: number
        example: 400
      message:
        type: string
        example: Bad Request